2017-03-08 00:47:58.645 [error] <0.179.0> gen_server <0.179.0> terminated with reason: bad record ofp_message in ofp_client:handle_call/3 line 194
2017-03-08 00:47:58.646 [error] <0.179.0> CRASH REPORT Process <0.179.0> with 0 neighbours exited with reason: bad record ofp_message in ofp_client:handle_call/3 line 194 in gen_server:terminate/7 line 826
2017-03-08 00:47:58.647 [error] <0.177.0> Supervisor {<0.177.0>,ofp_channel_sup} had child undefined started with ofp_client:start_link(ofp_channel_1, <<"ofp_channel_1">>, {remote_peer,{192,168,56,101},6653,tcp}, [{controlling_process,<0.172.0>},{version,4}]) at <0.179.0> exit with reason bad record ofp_message in ofp_client:handle_call/3 line 194 in context child_terminated
2017-03-08 14:42:53.361 [error] <0.119.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.124.0> exit with reason normal in context child_terminated
2017-03-08 14:42:53.383 [info] <0.7.0> Application lager started on node nonode@nohost
2017-03-08 14:42:53.384 [info] <0.7.0> Application eenum started on node nonode@nohost
2017-03-08 14:42:53.384 [info] <0.7.0> Application of_protocol started on node nonode@nohost
2017-03-08 14:42:53.384 [info] <0.7.0> Application of_msg_lib started on node nonode@nohost
2017-03-08 14:42:53.391 [info] <0.7.0> Application of_driver started on node nonode@nohost
2017-03-08 14:42:53.400 [info] <0.7.0> Application ofs_handler started on node nonode@nohost
2017-03-08 14:42:53.400 [info] <0.7.0> Application sdn_epc started on node nonode@nohost
2017-03-08 14:42:57.564 [info] <0.192.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50024. Connection : <0.192.0> 
2017-03-08 14:46:13.877 [error] <0.112.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.117.0> exit with reason normal in context child_terminated
2017-03-08 14:46:13.897 [info] <0.7.0> Application lager started on node nonode@nohost
2017-03-08 14:46:13.898 [info] <0.7.0> Application eenum started on node nonode@nohost
2017-03-08 14:46:13.898 [info] <0.7.0> Application of_protocol started on node nonode@nohost
2017-03-08 14:46:13.899 [info] <0.7.0> Application of_msg_lib started on node nonode@nohost
2017-03-08 14:46:13.905 [info] <0.7.0> Application of_driver started on node nonode@nohost
2017-03-08 14:46:13.915 [info] <0.7.0> Application ofs_handler started on node nonode@nohost
2017-03-08 14:46:13.915 [info] <0.7.0> Application sdn_epc started on node nonode@nohost
2017-03-08 14:46:20.564 [info] <0.185.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50036. Connection : <0.185.0> 
2017-03-08 14:46:25.604 [info] <0.185.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {timeout,{gen_server,call,[<0.186.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.185.0>,[]}]}}
2017-03-08 14:46:25.604 [warning] <0.185.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:46:25.605 [warning] <0.186.0>@ofs_handler_logic:terminate:239 [ofs_handler_logic] terminate datapathId("00:00:00:00:00:00:00:01") reason({timeout,{gen_server,call,[<0.186.0>,{async_subscribe,'Elixir.SdnEpc.OfshCalls',packet_in}]}})
2017-03-08 14:46:25.660 [error] <0.185.0> gen_server <0.185.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:46:25.660 [error] <0.185.0> CRASH REPORT Process <0.185.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:46:25.661 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.185.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:46:25.661 [error] <0.186.0> gen_server <0.186.0> terminated with reason: {timeout,{gen_server,call,[<0.186.0>,{async_subscribe,'Elixir.SdnEpc.OfshCalls',packet_in}]}} in gen_server:call/2 line 204
2017-03-08 14:46:25.662 [error] <0.186.0> CRASH REPORT Process <0.186.0> with 0 neighbours exited with reason: {timeout,{gen_server,call,[<0.186.0>,{async_subscribe,'Elixir.SdnEpc.OfshCalls',packet_in}]}} in gen_server:terminate/7 line 826
2017-03-08 14:46:25.662 [error] <0.180.0> Supervisor ofs_handler_logic_sup had child undefined started with {ofs_handler_logic,start_link,undefined} at <0.186.0> exit with reason {timeout,{gen_server,call,[<0.186.0>,{async_subscribe,'Elixir.SdnEpc.OfshCalls',packet_in}]}} in context child_terminated
2017-03-08 14:46:33.556 [info] <0.187.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50037. Connection : <0.187.0> 
2017-03-08 14:46:33.558 [warning] <0.187.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(already_connected)
2017-03-08 14:46:33.558 [info] <0.187.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {function_clause,[{ofs_handler_driver,terminate,[driver_closed_connection,undefined],[{file,"src/ofs_handler_driver.erl"},{line,90}]},{of_driver_connection,close_of_connection,2,[{file,"src/of_driver_connection.erl"},{line,481}]},{of_driver_connection,handle_message,2,[{file,"src/of_driver_connection.erl"},{line,350}]},{of_driver_connection,handle_messages,2,[{file,"src/of_driver_connection.erl"},{line,321}]},{of_driver_connection,do_handle_tcp,2,[{file,"src/of_driver_connection.erl"},{line,299}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-03-08 14:46:33.559 [warning] <0.187.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:46:33.560 [error] <0.187.0> gen_server <0.187.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:46:33.560 [error] <0.187.0> CRASH REPORT Process <0.187.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:46:33.561 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.187.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:46:41.556 [info] <0.188.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50038. Connection : <0.188.0> 
2017-03-08 14:46:46.558 [info] <0.188.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {timeout,{gen_server,call,[<0.189.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.188.0>,[]}]}}
2017-03-08 14:46:46.558 [warning] <0.188.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:46:46.559 [warning] <0.189.0>@ofs_handler_logic:terminate:239 [ofs_handler_logic] terminate datapathId("00:00:00:00:00:00:00:01") reason({timeout,{gen_server,call,[<0.189.0>,{async_subscribe,'Elixir.SdnEpc.OfshCalls',packet_in}]}})
2017-03-08 14:46:46.560 [error] <0.188.0> gen_server <0.188.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:46:46.560 [error] <0.188.0> CRASH REPORT Process <0.188.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:46:46.560 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.188.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:46:46.562 [error] <0.189.0> gen_server <0.189.0> terminated with reason: {timeout,{gen_server,call,[<0.189.0>,{async_subscribe,'Elixir.SdnEpc.OfshCalls',packet_in}]}} in gen_server:call/2 line 204
2017-03-08 14:46:46.562 [error] <0.189.0> CRASH REPORT Process <0.189.0> with 0 neighbours exited with reason: {timeout,{gen_server,call,[<0.189.0>,{async_subscribe,'Elixir.SdnEpc.OfshCalls',packet_in}]}} in gen_server:terminate/7 line 826
2017-03-08 14:46:46.562 [error] <0.180.0> Supervisor ofs_handler_logic_sup had child undefined started with {ofs_handler_logic,start_link,undefined} at <0.189.0> exit with reason {timeout,{gen_server,call,[<0.189.0>,{async_subscribe,'Elixir.SdnEpc.OfshCalls',packet_in}]}} in context child_terminated
2017-03-08 14:46:54.557 [info] <0.190.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50039. Connection : <0.190.0> 
2017-03-08 14:46:54.559 [warning] <0.190.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(already_connected)
2017-03-08 14:46:54.559 [info] <0.190.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {function_clause,[{ofs_handler_driver,terminate,[driver_closed_connection,undefined],[{file,"src/ofs_handler_driver.erl"},{line,90}]},{of_driver_connection,close_of_connection,2,[{file,"src/of_driver_connection.erl"},{line,481}]},{of_driver_connection,handle_message,2,[{file,"src/of_driver_connection.erl"},{line,350}]},{of_driver_connection,handle_messages,2,[{file,"src/of_driver_connection.erl"},{line,321}]},{of_driver_connection,do_handle_tcp,2,[{file,"src/of_driver_connection.erl"},{line,299}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-03-08 14:46:54.559 [warning] <0.190.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:46:54.561 [error] <0.190.0> gen_server <0.190.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:46:54.561 [error] <0.190.0> CRASH REPORT Process <0.190.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:46:54.562 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.190.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:47:02.556 [info] <0.191.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50040. Connection : <0.191.0> 
2017-03-08 14:47:22.349 [error] <0.112.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.117.0> exit with reason normal in context child_terminated
2017-03-08 14:47:22.369 [info] <0.7.0> Application lager started on node nonode@nohost
2017-03-08 14:47:22.370 [info] <0.7.0> Application eenum started on node nonode@nohost
2017-03-08 14:47:22.370 [info] <0.7.0> Application of_protocol started on node nonode@nohost
2017-03-08 14:47:22.371 [info] <0.7.0> Application of_msg_lib started on node nonode@nohost
2017-03-08 14:47:22.377 [info] <0.7.0> Application of_driver started on node nonode@nohost
2017-03-08 14:47:22.387 [info] <0.7.0> Application ofs_handler started on node nonode@nohost
2017-03-08 14:47:22.387 [info] <0.7.0> Application sdn_epc started on node nonode@nohost
2017-03-08 14:47:29.563 [info] <0.185.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50043. Connection : <0.185.0> 
2017-03-08 14:48:33.095 [error] <0.112.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.117.0> exit with reason normal in context child_terminated
2017-03-08 14:48:33.115 [info] <0.7.0> Application lager started on node nonode@nohost
2017-03-08 14:48:33.116 [info] <0.7.0> Application eenum started on node nonode@nohost
2017-03-08 14:48:33.116 [info] <0.7.0> Application of_protocol started on node nonode@nohost
2017-03-08 14:48:33.117 [info] <0.7.0> Application of_msg_lib started on node nonode@nohost
2017-03-08 14:48:33.123 [info] <0.7.0> Application of_driver started on node nonode@nohost
2017-03-08 14:48:33.133 [info] <0.7.0> Application ofs_handler started on node nonode@nohost
2017-03-08 14:48:33.133 [info] <0.7.0> Application sdn_epc started on node nonode@nohost
2017-03-08 14:48:40.561 [info] <0.185.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50048. Connection : <0.185.0> 
2017-03-08 14:50:02.947 [warning] <0.187.0>@ofs_handler_message:terminate:122 [ofs_handler_message] terminate reason({#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {packet_in,0,[{buffer_id,256},{reason,no_match},{table_id,0},{cookie,<<0,0,0,0,0,0,0,0>>},{match,[{in_port,<<0,0,0,1>>}]},{data,<<255,255,255,255,255,255,250,207,87,165,254,154,8,6,0,1,8,0,6,4,0,1,250,207,87,165,254,154,10,0,0,1,0,0,0,0,0,0,10,0,0,2>>}]}},[{'Elixir.String.Chars','impl_for!',1,[{file,"lib/string/chars.ex"},{line,3}]},{'Elixir.String.Chars',to_string,1,[{file,"lib/string/chars.ex"},{line,17}]},{'Elixir.SdnEpc.OfshCalls',handle_message,2,[{file,"lib/sdn_epc/ofs_calls.ex"},{line,12}]},{ofs_handler_message,notify_subscriber,3,[{file,"src/ofs_handler_message.erl"},{line,157}]},{ofs_handler_message,handle_call,3,[{file,"src/ofs_handler_message.erl"},{line,96}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]})
2017-03-08 14:50:02.948 [info] <0.185.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {{undef,[{'Elixir.SdnEpc.OfshCalls',terminate,["00:00:00:00:00:00:00:01"],[]},{ofs_handler_message,terminate,2,[{file,"src/ofs_handler_message.erl"},{line,125}]},{gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,643}]},{gen_server,terminate,7,[{file,"gen_server.erl"},{line,809}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{gen_server,call,[<0.187.0>,{message,<0.185.0>,{ofp_message,4,packet_in,0,{ofp_packet_in,256,42,no_match,0,<<0,0,0,0,0,0,0,0>>,{ofp_match,[{ofp_field,openflow_basic,in_port,false,<<0,0,0,1>>,undefined}]},<<255,255,255,255,255,255,250,207,87,165,254,154,8,6,0,1,8,0,6,4,0,1,250,207,87,165,254,154,10,0,0,1,0,0,0,0,0,0,10,0,0,2>>}}}]}}
2017-03-08 14:50:02.948 [warning] <0.185.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(gen_server_terminate)
2017-03-08 14:50:02.998 [error] <0.187.0> gen_server <0.187.0> terminated with reason: call to undefined function 'Elixir.SdnEpc.OfshCalls':terminate/1 from ofs_handler_message:terminate/2 line 125
2017-03-08 14:50:03.000 [error] <0.187.0> CRASH REPORT Process <0.187.0> with 1 neighbours exited with reason: call to undefined function 'Elixir.SdnEpc.OfshCalls':terminate("00:00:00:00:00:00:00:01") in gen_server:terminate/7 line 814
2017-03-08 14:50:03.000 [error] <0.181.0> Supervisor ofs_handler_message_sup had child undefined started with {ofs_handler_message,start_link,undefined} at <0.187.0> exit with reason call to undefined function 'Elixir.SdnEpc.OfshCalls':terminate("00:00:00:00:00:00:00:01") in context child_terminated
2017-03-08 14:50:03.000 [error] <0.180.0> Supervisor ofs_handler_logic_sup had child undefined started with {ofs_handler_logic,start_link,undefined} at <0.186.0> exit with reason call to undefined function 'Elixir.SdnEpc.OfshCalls':terminate("00:00:00:00:00:00:00:01") in context child_terminated
2017-03-08 14:50:03.009 [error] <0.185.0> gen_server <0.185.0> terminated with reason: no such process or port in call to gen_server:call(<0.186.0>, {terminate,<0.187.0>,<0.185.0>,driver_closed_connection}) in gen_server:call/2 line 204
2017-03-08 14:50:03.009 [error] <0.185.0> CRASH REPORT Process <0.185.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.186.0>, {terminate,<0.187.0>,<0.185.0>,driver_closed_connection}) in gen_server:terminate/7 line 814
2017-03-08 14:50:03.009 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.185.0> exit with reason no such process or port in call to gen_server:call(<0.186.0>, {terminate,<0.187.0>,<0.185.0>,driver_closed_connection}) in context child_terminated
2017-03-08 14:50:03.555 [info] <0.191.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50049. Connection : <0.191.0> 
2017-03-08 14:50:03.557 [info] <0.191.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {noproc,{gen_server,call,[<0.186.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.191.0>,[]}]}}
2017-03-08 14:50:03.557 [warning] <0.191.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:50:03.562 [error] <0.191.0> gen_server <0.191.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:50:03.562 [error] <0.191.0> CRASH REPORT Process <0.191.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:50:03.562 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.191.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:50:05.557 [info] <0.192.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50050. Connection : <0.192.0> 
2017-03-08 14:50:05.558 [warning] <0.192.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(already_connected)
2017-03-08 14:50:05.558 [info] <0.192.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {function_clause,[{ofs_handler_driver,terminate,[driver_closed_connection,undefined],[{file,"src/ofs_handler_driver.erl"},{line,90}]},{of_driver_connection,close_of_connection,2,[{file,"src/of_driver_connection.erl"},{line,481}]},{of_driver_connection,handle_message,2,[{file,"src/of_driver_connection.erl"},{line,350}]},{of_driver_connection,handle_messages,2,[{file,"src/of_driver_connection.erl"},{line,321}]},{of_driver_connection,do_handle_tcp,2,[{file,"src/of_driver_connection.erl"},{line,299}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-03-08 14:50:05.558 [warning] <0.192.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:50:05.560 [error] <0.192.0> gen_server <0.192.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:50:05.560 [error] <0.192.0> CRASH REPORT Process <0.192.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:50:05.560 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.192.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:50:09.556 [info] <0.193.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50051. Connection : <0.193.0> 
2017-03-08 14:50:09.557 [info] <0.193.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {noproc,{gen_server,call,[<0.186.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.193.0>,[]}]}}
2017-03-08 14:50:09.557 [warning] <0.193.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:50:09.559 [error] <0.193.0> gen_server <0.193.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:50:09.559 [error] <0.193.0> CRASH REPORT Process <0.193.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:50:09.559 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.193.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:50:17.556 [info] <0.194.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50052. Connection : <0.194.0> 
2017-03-08 14:50:17.557 [warning] <0.194.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(already_connected)
2017-03-08 14:50:17.558 [info] <0.194.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {function_clause,[{ofs_handler_driver,terminate,[driver_closed_connection,undefined],[{file,"src/ofs_handler_driver.erl"},{line,90}]},{of_driver_connection,close_of_connection,2,[{file,"src/of_driver_connection.erl"},{line,481}]},{of_driver_connection,handle_message,2,[{file,"src/of_driver_connection.erl"},{line,350}]},{of_driver_connection,handle_messages,2,[{file,"src/of_driver_connection.erl"},{line,321}]},{of_driver_connection,do_handle_tcp,2,[{file,"src/of_driver_connection.erl"},{line,299}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-03-08 14:50:17.558 [warning] <0.194.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:50:17.559 [error] <0.194.0> gen_server <0.194.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:50:17.559 [error] <0.194.0> CRASH REPORT Process <0.194.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:50:17.560 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.194.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:50:25.555 [info] <0.195.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50053. Connection : <0.195.0> 
2017-03-08 14:50:25.556 [info] <0.195.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {noproc,{gen_server,call,[<0.186.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.195.0>,[]}]}}
2017-03-08 14:50:25.556 [warning] <0.195.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:50:25.558 [error] <0.195.0> gen_server <0.195.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:50:25.559 [error] <0.195.0> CRASH REPORT Process <0.195.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:50:25.559 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.195.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:50:33.556 [info] <0.196.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50054. Connection : <0.196.0> 
2017-03-08 14:50:33.557 [warning] <0.196.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(already_connected)
2017-03-08 14:50:33.558 [info] <0.196.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {function_clause,[{ofs_handler_driver,terminate,[driver_closed_connection,undefined],[{file,"src/ofs_handler_driver.erl"},{line,90}]},{of_driver_connection,close_of_connection,2,[{file,"src/of_driver_connection.erl"},{line,481}]},{of_driver_connection,handle_message,2,[{file,"src/of_driver_connection.erl"},{line,350}]},{of_driver_connection,handle_messages,2,[{file,"src/of_driver_connection.erl"},{line,321}]},{of_driver_connection,do_handle_tcp,2,[{file,"src/of_driver_connection.erl"},{line,299}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-03-08 14:50:33.558 [warning] <0.196.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:50:33.559 [error] <0.196.0> gen_server <0.196.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:50:33.559 [error] <0.196.0> CRASH REPORT Process <0.196.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:50:33.560 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.196.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:50:41.557 [info] <0.197.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50055. Connection : <0.197.0> 
2017-03-08 14:50:41.558 [info] <0.197.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {noproc,{gen_server,call,[<0.186.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.197.0>,[]}]}}
2017-03-08 14:50:41.558 [warning] <0.197.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:50:41.560 [error] <0.197.0> gen_server <0.197.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:50:41.560 [error] <0.197.0> CRASH REPORT Process <0.197.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:50:41.560 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.197.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:50:49.556 [info] <0.198.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50056. Connection : <0.198.0> 
2017-03-08 14:50:49.558 [warning] <0.198.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(already_connected)
2017-03-08 14:50:49.558 [info] <0.198.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {function_clause,[{ofs_handler_driver,terminate,[driver_closed_connection,undefined],[{file,"src/ofs_handler_driver.erl"},{line,90}]},{of_driver_connection,close_of_connection,2,[{file,"src/of_driver_connection.erl"},{line,481}]},{of_driver_connection,handle_message,2,[{file,"src/of_driver_connection.erl"},{line,350}]},{of_driver_connection,handle_messages,2,[{file,"src/of_driver_connection.erl"},{line,321}]},{of_driver_connection,do_handle_tcp,2,[{file,"src/of_driver_connection.erl"},{line,299}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-03-08 14:50:49.558 [warning] <0.198.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:50:49.560 [error] <0.198.0> gen_server <0.198.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:50:49.561 [error] <0.198.0> CRASH REPORT Process <0.198.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:50:49.561 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.198.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:50:57.556 [info] <0.199.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50057. Connection : <0.199.0> 
2017-03-08 14:50:57.558 [info] <0.199.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {noproc,{gen_server,call,[<0.186.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.199.0>,[]}]}}
2017-03-08 14:50:57.558 [warning] <0.199.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:50:57.559 [error] <0.199.0> gen_server <0.199.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:50:57.559 [error] <0.199.0> CRASH REPORT Process <0.199.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:50:57.560 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.199.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:51:05.556 [info] <0.200.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50058. Connection : <0.200.0> 
2017-03-08 14:51:05.557 [warning] <0.200.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(already_connected)
2017-03-08 14:51:05.558 [info] <0.200.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {function_clause,[{ofs_handler_driver,terminate,[driver_closed_connection,undefined],[{file,"src/ofs_handler_driver.erl"},{line,90}]},{of_driver_connection,close_of_connection,2,[{file,"src/of_driver_connection.erl"},{line,481}]},{of_driver_connection,handle_message,2,[{file,"src/of_driver_connection.erl"},{line,350}]},{of_driver_connection,handle_messages,2,[{file,"src/of_driver_connection.erl"},{line,321}]},{of_driver_connection,do_handle_tcp,2,[{file,"src/of_driver_connection.erl"},{line,299}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-03-08 14:51:05.558 [warning] <0.200.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:51:05.560 [error] <0.200.0> gen_server <0.200.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:51:05.560 [error] <0.200.0> CRASH REPORT Process <0.200.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:51:05.560 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.200.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:51:13.556 [info] <0.201.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50059. Connection : <0.201.0> 
2017-03-08 14:51:13.557 [info] <0.201.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {noproc,{gen_server,call,[<0.186.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.201.0>,[]}]}}
2017-03-08 14:51:13.557 [warning] <0.201.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:51:13.558 [error] <0.201.0> gen_server <0.201.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:51:13.558 [error] <0.201.0> CRASH REPORT Process <0.201.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:51:13.559 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.201.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:51:21.556 [info] <0.202.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50060. Connection : <0.202.0> 
2017-03-08 14:51:21.557 [warning] <0.202.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(already_connected)
2017-03-08 14:51:21.558 [info] <0.202.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {function_clause,[{ofs_handler_driver,terminate,[driver_closed_connection,undefined],[{file,"src/ofs_handler_driver.erl"},{line,90}]},{of_driver_connection,close_of_connection,2,[{file,"src/of_driver_connection.erl"},{line,481}]},{of_driver_connection,handle_message,2,[{file,"src/of_driver_connection.erl"},{line,350}]},{of_driver_connection,handle_messages,2,[{file,"src/of_driver_connection.erl"},{line,321}]},{of_driver_connection,do_handle_tcp,2,[{file,"src/of_driver_connection.erl"},{line,299}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-03-08 14:51:21.558 [warning] <0.202.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:51:21.559 [error] <0.202.0> gen_server <0.202.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:51:21.559 [error] <0.202.0> CRASH REPORT Process <0.202.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:51:21.560 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.202.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:51:29.556 [info] <0.203.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50061. Connection : <0.203.0> 
2017-03-08 14:51:29.557 [info] <0.203.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {noproc,{gen_server,call,[<0.186.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.203.0>,[]}]}}
2017-03-08 14:51:29.557 [warning] <0.203.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:51:29.558 [error] <0.203.0> gen_server <0.203.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:51:29.558 [error] <0.203.0> CRASH REPORT Process <0.203.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:51:29.558 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.203.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:51:37.556 [info] <0.205.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50062. Connection : <0.205.0> 
2017-03-08 14:51:37.560 [warning] <0.205.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(already_connected)
2017-03-08 14:51:37.561 [info] <0.205.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {function_clause,[{ofs_handler_driver,terminate,[driver_closed_connection,undefined],[{file,"src/ofs_handler_driver.erl"},{line,90}]},{of_driver_connection,close_of_connection,2,[{file,"src/of_driver_connection.erl"},{line,481}]},{of_driver_connection,handle_message,2,[{file,"src/of_driver_connection.erl"},{line,350}]},{of_driver_connection,handle_messages,2,[{file,"src/of_driver_connection.erl"},{line,321}]},{of_driver_connection,do_handle_tcp,2,[{file,"src/of_driver_connection.erl"},{line,299}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-03-08 14:51:37.561 [warning] <0.205.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:51:37.562 [error] <0.205.0> gen_server <0.205.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:51:37.563 [error] <0.205.0> CRASH REPORT Process <0.205.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:51:37.563 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.205.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:51:45.556 [info] <0.206.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50063. Connection : <0.206.0> 
2017-03-08 14:51:45.556 [info] <0.206.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {noproc,{gen_server,call,[<0.186.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.206.0>,[]}]}}
2017-03-08 14:51:45.556 [warning] <0.206.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:51:45.557 [error] <0.206.0> gen_server <0.206.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:51:45.557 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:51:45.557 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.206.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:51:53.555 [info] <0.207.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50064. Connection : <0.207.0> 
2017-03-08 14:51:53.557 [warning] <0.207.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(already_connected)
2017-03-08 14:51:53.557 [info] <0.207.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {function_clause,[{ofs_handler_driver,terminate,[driver_closed_connection,undefined],[{file,"src/ofs_handler_driver.erl"},{line,90}]},{of_driver_connection,close_of_connection,2,[{file,"src/of_driver_connection.erl"},{line,481}]},{of_driver_connection,handle_message,2,[{file,"src/of_driver_connection.erl"},{line,350}]},{of_driver_connection,handle_messages,2,[{file,"src/of_driver_connection.erl"},{line,321}]},{of_driver_connection,do_handle_tcp,2,[{file,"src/of_driver_connection.erl"},{line,299}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-03-08 14:51:53.557 [warning] <0.207.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:51:53.559 [error] <0.207.0> gen_server <0.207.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:51:53.559 [error] <0.207.0> CRASH REPORT Process <0.207.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:51:53.559 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.207.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:52:01.556 [info] <0.208.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50065. Connection : <0.208.0> 
2017-03-08 14:52:01.557 [info] <0.208.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {noproc,{gen_server,call,[<0.186.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.208.0>,[]}]}}
2017-03-08 14:52:01.557 [warning] <0.208.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:52:01.558 [error] <0.208.0> gen_server <0.208.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:52:01.558 [error] <0.208.0> CRASH REPORT Process <0.208.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:52:01.558 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.208.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:52:09.556 [info] <0.209.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50066. Connection : <0.209.0> 
2017-03-08 14:52:09.557 [warning] <0.209.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(already_connected)
2017-03-08 14:52:09.557 [info] <0.209.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {function_clause,[{ofs_handler_driver,terminate,[driver_closed_connection,undefined],[{file,"src/ofs_handler_driver.erl"},{line,90}]},{of_driver_connection,close_of_connection,2,[{file,"src/of_driver_connection.erl"},{line,481}]},{of_driver_connection,handle_message,2,[{file,"src/of_driver_connection.erl"},{line,350}]},{of_driver_connection,handle_messages,2,[{file,"src/of_driver_connection.erl"},{line,321}]},{of_driver_connection,do_handle_tcp,2,[{file,"src/of_driver_connection.erl"},{line,299}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-03-08 14:52:09.557 [warning] <0.209.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:52:09.559 [error] <0.209.0> gen_server <0.209.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:52:09.559 [error] <0.209.0> CRASH REPORT Process <0.209.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:52:09.560 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.209.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:52:17.556 [info] <0.210.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50067. Connection : <0.210.0> 
2017-03-08 14:52:17.557 [info] <0.210.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {noproc,{gen_server,call,[<0.186.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.210.0>,[]}]}}
2017-03-08 14:52:17.557 [warning] <0.210.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:52:17.559 [error] <0.210.0> gen_server <0.210.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:52:17.559 [error] <0.210.0> CRASH REPORT Process <0.210.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:52:17.559 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.210.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:52:25.556 [info] <0.211.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50068. Connection : <0.211.0> 
2017-03-08 14:52:25.558 [warning] <0.211.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(already_connected)
2017-03-08 14:52:25.558 [info] <0.211.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {function_clause,[{ofs_handler_driver,terminate,[driver_closed_connection,undefined],[{file,"src/ofs_handler_driver.erl"},{line,90}]},{of_driver_connection,close_of_connection,2,[{file,"src/of_driver_connection.erl"},{line,481}]},{of_driver_connection,handle_message,2,[{file,"src/of_driver_connection.erl"},{line,350}]},{of_driver_connection,handle_messages,2,[{file,"src/of_driver_connection.erl"},{line,321}]},{of_driver_connection,do_handle_tcp,2,[{file,"src/of_driver_connection.erl"},{line,299}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-03-08 14:52:25.559 [warning] <0.211.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:52:25.560 [error] <0.211.0> gen_server <0.211.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:52:25.560 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:52:25.560 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.211.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:52:33.555 [info] <0.212.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50069. Connection : <0.212.0> 
2017-03-08 14:52:33.558 [info] <0.212.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {noproc,{gen_server,call,[<0.186.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.212.0>,[]}]}}
2017-03-08 14:52:33.558 [warning] <0.212.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:52:33.560 [error] <0.212.0> gen_server <0.212.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:52:33.560 [error] <0.212.0> CRASH REPORT Process <0.212.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:52:33.560 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.212.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:52:41.555 [info] <0.213.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50070. Connection : <0.213.0> 
2017-03-08 14:52:41.556 [warning] <0.213.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(already_connected)
2017-03-08 14:52:41.556 [info] <0.213.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {function_clause,[{ofs_handler_driver,terminate,[driver_closed_connection,undefined],[{file,"src/ofs_handler_driver.erl"},{line,90}]},{of_driver_connection,close_of_connection,2,[{file,"src/of_driver_connection.erl"},{line,481}]},{of_driver_connection,handle_message,2,[{file,"src/of_driver_connection.erl"},{line,350}]},{of_driver_connection,handle_messages,2,[{file,"src/of_driver_connection.erl"},{line,321}]},{of_driver_connection,do_handle_tcp,2,[{file,"src/of_driver_connection.erl"},{line,299}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-03-08 14:52:41.557 [warning] <0.213.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:52:41.558 [error] <0.213.0> gen_server <0.213.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:52:41.558 [error] <0.213.0> CRASH REPORT Process <0.213.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:52:41.559 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.213.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 14:52:49.555 [info] <0.214.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50071. Connection : <0.214.0> 
2017-03-08 14:52:49.556 [info] <0.214.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {noproc,{gen_server,call,[<0.186.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.214.0>,[]}]}}
2017-03-08 14:52:49.556 [warning] <0.214.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 14:52:49.558 [error] <0.214.0> gen_server <0.214.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 14:52:49.558 [error] <0.214.0> CRASH REPORT Process <0.214.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 14:52:49.558 [error] <0.172.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.214.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 15:00:32.689 [error] <0.101.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.106.0> exit with reason normal in context child_terminated
2017-03-08 15:00:32.708 [info] <0.7.0> Application lager started on node nonode@nohost
2017-03-08 15:00:32.709 [info] <0.7.0> Application eenum started on node nonode@nohost
2017-03-08 15:00:32.709 [info] <0.7.0> Application of_protocol started on node nonode@nohost
2017-03-08 15:00:32.710 [info] <0.7.0> Application of_msg_lib started on node nonode@nohost
2017-03-08 15:00:32.716 [info] <0.7.0> Application of_driver started on node nonode@nohost
2017-03-08 15:00:32.725 [info] <0.7.0> Application ofs_handler started on node nonode@nohost
2017-03-08 15:00:32.725 [info] <0.7.0> Application sdn_epc started on node nonode@nohost
2017-03-08 15:00:33.559 [info] <0.174.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50129. Connection : <0.174.0> 
2017-03-08 15:01:05.923 [warning] <0.176.0>@ofs_handler_message:terminate:122 [ofs_handler_message] terminate reason({#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {packet_in,0,[{buffer_id,256},{reason,no_match},{table_id,0},{cookie,<<0,0,0,0,0,0,0,0>>},{match,[{in_port,<<0,0,0,1>>}]},{data,<<255,255,255,255,255,255,250,207,87,165,254,154,8,6,0,1,8,0,6,4,0,1,250,207,87,165,254,154,10,0,0,1,0,0,0,0,0,0,10,0,0,2>>}]}},[{'Elixir.String.Chars','impl_for!',1,[{file,"lib/string/chars.ex"},{line,3}]},{'Elixir.String.Chars',to_string,1,[{file,"lib/string/chars.ex"},{line,17}]},{'Elixir.SdnEpc.OfshCalls',handle_message,2,[{file,"lib/sdn_epc/ofs_calls.ex"},{line,12}]},{ofs_handler_message,notify_subscriber,3,[{file,"src/ofs_handler_message.erl"},{line,157}]},{ofs_handler_message,handle_call,3,[{file,"src/ofs_handler_message.erl"},{line,96}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]})
2017-03-08 15:01:05.924 [info] <0.174.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {{undef,[{'Elixir.SdnEpc.OfshCalls',terminate,["00:00:00:00:00:00:00:01"],[]},{ofs_handler_message,terminate,2,[{file,"src/ofs_handler_message.erl"},{line,125}]},{gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,643}]},{gen_server,terminate,7,[{file,"gen_server.erl"},{line,809}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{gen_server,call,[<0.176.0>,{message,<0.174.0>,{ofp_message,4,packet_in,0,{ofp_packet_in,256,42,no_match,0,<<0,0,0,0,0,0,0,0>>,{ofp_match,[{ofp_field,openflow_basic,in_port,false,<<0,0,0,1>>,undefined}]},<<255,255,255,255,255,255,250,207,87,165,254,154,8,6,0,1,8,0,6,4,0,1,250,207,87,165,254,154,10,0,0,1,0,0,0,0,0,0,10,0,0,2>>}}}]}}
2017-03-08 15:01:05.924 [warning] <0.174.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(gen_server_terminate)
2017-03-08 15:01:05.962 [error] <0.176.0> gen_server <0.176.0> terminated with reason: call to undefined function 'Elixir.SdnEpc.OfshCalls':terminate/1 from ofs_handler_message:terminate/2 line 125
2017-03-08 15:01:05.962 [error] <0.176.0> CRASH REPORT Process <0.176.0> with 1 neighbours exited with reason: call to undefined function 'Elixir.SdnEpc.OfshCalls':terminate("00:00:00:00:00:00:00:01") in gen_server:terminate/7 line 814
2017-03-08 15:01:05.962 [error] <0.170.0> Supervisor ofs_handler_message_sup had child undefined started with {ofs_handler_message,start_link,undefined} at <0.176.0> exit with reason call to undefined function 'Elixir.SdnEpc.OfshCalls':terminate("00:00:00:00:00:00:00:01") in context child_terminated
2017-03-08 15:01:05.962 [error] <0.169.0> Supervisor ofs_handler_logic_sup had child undefined started with {ofs_handler_logic,start_link,undefined} at <0.175.0> exit with reason call to undefined function 'Elixir.SdnEpc.OfshCalls':terminate("00:00:00:00:00:00:00:01") in context child_terminated
2017-03-08 15:01:05.975 [error] <0.174.0> gen_server <0.174.0> terminated with reason: no such process or port in call to gen_server:call(<0.175.0>, {terminate,<0.176.0>,<0.174.0>,driver_closed_connection}) in gen_server:call/2 line 204
2017-03-08 15:01:05.975 [error] <0.174.0> CRASH REPORT Process <0.174.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.175.0>, {terminate,<0.176.0>,<0.174.0>,driver_closed_connection}) in gen_server:terminate/7 line 814
2017-03-08 15:01:05.975 [error] <0.161.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.174.0> exit with reason no such process or port in call to gen_server:call(<0.175.0>, {terminate,<0.176.0>,<0.174.0>,driver_closed_connection}) in context child_terminated
2017-03-08 15:01:06.554 [info] <0.181.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50130. Connection : <0.181.0> 
2017-03-08 15:01:06.555 [info] <0.181.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {noproc,{gen_server,call,[<0.175.0>,{init,{192,168,56,101},"00:00:00:00:00:00:00:01",{ofp_features_reply,<<0,0,0,0,0,1>>,0,256,254,0,[flow_stats,table_stats,port_stats,queue_stats]},4,<0.181.0>,[]}]}}
2017-03-08 15:01:06.555 [warning] <0.181.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 15:01:06.558 [error] <0.181.0> gen_server <0.181.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 15:01:06.558 [error] <0.181.0> CRASH REPORT Process <0.181.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 15:01:06.558 [error] <0.161.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.181.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 15:01:08.554 [info] <0.182.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50131. Connection : <0.182.0> 
2017-03-08 15:01:08.556 [warning] <0.182.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac("00:00:00:00:00:00:00:01") aux_id(0) reason(already_connected)
2017-03-08 15:01:08.556 [info] <0.182.0>@of_driver_connection:terminate:179 [of_driver_connection] terminating (crash): {function_clause,[{ofs_handler_driver,terminate,[driver_closed_connection,undefined],[{file,"src/ofs_handler_driver.erl"},{line,90}]},{of_driver_connection,close_of_connection,2,[{file,"src/of_driver_connection.erl"},{line,481}]},{of_driver_connection,handle_message,2,[{file,"src/of_driver_connection.erl"},{line,350}]},{of_driver_connection,handle_messages,2,[{file,"src/of_driver_connection.erl"},{line,321}]},{of_driver_connection,do_handle_tcp,2,[{file,"src/of_driver_connection.erl"},{line,299}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-03-08 15:01:08.556 [warning] <0.182.0>@of_driver_connection:close_of_connection:477 connection terminated: datapath_mac(undefined) aux_id(0) reason(gen_server_terminate)
2017-03-08 15:01:08.557 [error] <0.182.0> gen_server <0.182.0> terminated with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90
2017-03-08 15:01:08.558 [error] <0.182.0> CRASH REPORT Process <0.182.0> with 0 neighbours exited with reason: no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in gen_server:terminate/7 line 814
2017-03-08 15:01:08.558 [error] <0.161.0> Supervisor of_driver_connection_sup had child undefined started with {of_driver_connection,start_link,undefined} at <0.182.0> exit with reason no function clause matching ofs_handler_driver:terminate(driver_closed_connection, undefined) line 90 in context child_terminated
2017-03-08 15:14:14.419 [error] <0.119.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.124.0> exit with reason normal in context child_terminated
2017-03-08 15:14:14.439 [info] <0.7.0> Application lager started on node nonode@nohost
2017-03-08 15:14:14.440 [info] <0.7.0> Application eenum started on node nonode@nohost
2017-03-08 15:14:14.440 [info] <0.7.0> Application of_protocol started on node nonode@nohost
2017-03-08 15:14:14.441 [info] <0.7.0> Application of_msg_lib started on node nonode@nohost
2017-03-08 15:14:14.447 [info] <0.7.0> Application of_driver started on node nonode@nohost
2017-03-08 15:14:14.456 [info] <0.7.0> Application ofs_handler started on node nonode@nohost
2017-03-08 15:14:14.457 [info] <0.7.0> Application sdn_epc started on node nonode@nohost
2017-03-08 15:14:16.557 [info] <0.192.0>@of_driver_connection:init:98 Connected to Switch on 192.168.56.101:50230. Connection : <0.192.0> 
